#include "OfflineManager.hpp"
#include <ctime>
namespace ols {
bool Manager::save(GJGameLevel* level){ if(!level||level->m_levelID<=0||level->m_levelString.empty())return false; Mod::get()->setSavedValue(keyData(level->m_levelID), level->m_levelString); matjson::Value meta; meta["name"]=level->m_levelName; meta["author"]=level->m_creatorName; meta["id"]=level->m_levelID; meta["savedAt"]=std::time(nullptr); Mod::get()->setSavedValue(keyMeta(level->m_levelID), meta); auto list=Mod::get()->getSavedValue<std::vector<int>>("saved_ids",{}); if(std::find(list.begin(),list.end(),level->m_levelID)==list.end()){list.push_back(level->m_levelID); Mod::get()->setSavedValue("saved_ids",list);} return true;}
bool Manager::remove(int levelID){ Mod::get()->setSavedValue(keyData(levelID),""); Mod::get()->setSavedValue(keyMeta(levelID),matjson::Value()); auto list=Mod::get()->getSavedValue<std::vector<int>>("saved_ids",{}); list.erase(std::remove(list.begin(),list.end(),levelID),list.end()); Mod::get()->setSavedValue("saved_ids",list); return true;}
bool Manager::isSaved(int levelID){ return !Mod::get()->getSavedValue<std::string>(keyData(levelID),"").empty();}
std::string Manager::getData(int levelID){ return Mod::get()->getSavedValue<std::string>(keyData(levelID),"");}
std::vector<LevelMeta> Manager::getAll(){ std::vector<LevelMeta> out; auto list=Mod::get()->getSavedValue<std::vector<int>>("saved_ids",{}); for(int id:list){ auto meta=Mod::get()->getSavedValue<matjson::Value>(keyMeta(id),matjson::Value()); if(meta.isNull()) continue; LevelMeta m; m.id=id; m.name=meta["name"].asString().unwrapOr("Unknown"); m.author=meta["author"].asString().unwrapOr("?"); m.savedAt=meta["savedAt"].asInt().unwrapOr(0); out.push_back(m);} std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.savedAt>b.savedAt;}); return out;}
bool Manager::exportGmd(int levelID, std::filesystem::path outDir){ auto data=getData(levelID); if(data.empty()) return false; std::filesystem::create_directories(outDir); std::ofstream out(outDir / fmt::format("{}.gmd",levelID)); out<<data; return out.good();}
}
