#include "RecordsManager.hpp"
#include <ctime>
namespace ols {
static std::string recKey(int id){return fmt::format("record_{}",id);}
LevelRecord RecordsManager::load(int levelID){ auto v=Mod::get()->getSavedValue<matjson::Value>(recKey(levelID),matjson::Value()); LevelRecord r; r.levelID=levelID; if(v.isNull()) return r; r.normalPercent=v["normalPercent"].asInt().unwrapOr(0); r.practicePercent=v["practicePercent"].asInt().unwrapOr(0); r.attempts=v["attempts"].asInt().unwrapOr(0); r.jumps=v["jumps"].asInt().unwrapOr(0); r.lastPlayed=v["lastPlayed"].asInt().unwrapOr(0); auto coins=v["coins"]; if(coins.isArray()){ auto a=coins.asArray().unwrap(); for(size_t i=0;i<3 && i<a.size();i++) r.coins[i]=a[i].asBool().unwrapOr(false);} return r;}
void RecordsManager::save(const LevelRecord& rec){ matjson::Value v; v["normalPercent"]=rec.normalPercent; v["practicePercent"]=rec.practicePercent; v["attempts"]=rec.attempts; v["jumps"]=rec.jumps; v["lastPlayed"]=rec.lastPlayed; v["coins"]=matjson::Array{rec.coins[0],rec.coins[1],rec.coins[2]}; Mod::get()->setSavedValue(recKey(rec.levelID),v); auto idx=Mod::get()->getSavedValue<std::vector<int>>("record_ids",{}); if(std::find(idx.begin(),idx.end(),rec.levelID)==idx.end()){idx.push_back(rec.levelID); Mod::get()->setSavedValue("record_ids",idx);} }
void RecordsManager::updateFromPlayLayer(GJGameLevel* level, int percent, bool isPractice){ if(!Mod::get()->getSettingValue<bool>("save-records")) return; if(!level||level->m_levelID<=0) return; auto rec=load(level->m_levelID); bool improved=false; if(isPractice && Mod::get()->getSettingValue<bool>("save-practice")){ if(percent>rec.practicePercent){rec.practicePercent=percent; improved=true;}} else if(!isPractice){ if(percent>rec.normalPercent){rec.normalPercent=percent; improved=true;}} rec.attempts=level->m_attempts; rec.jumps=level->m_jumps; rec.lastPlayed=std::time(nullptr); if(Mod::get()->getSettingValue<bool>("save-coins")){ rec.coins[0]=level->m_coinsVerified>0||level->m_hasCoin1; rec.coins[1]=level->m_coinsVerified>1||level->m_hasCoin2; rec.coins[2]=level->m_coinsVerified>2||level->m_hasCoin3;} save(rec); if(improved && Mod::get()->getSettingValue<bool>("record-notify")){ Notification::create(fmt::format("Новый рекорд: {}%",percent), NotificationIcon::Success)->show(); } }
std::vector<LevelRecord> RecordsManager::getAll(){ std::vector<LevelRecord> out; auto idx=Mod::get()->getSavedValue<std::vector<int>>("record_ids",{}); for(int id:idx) out.push_back(load(id)); std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.normalPercent>b.normalPercent;}); return out;}
bool RecordsManager::exportJson(std::filesystem::path out){ auto records=getAll(); matjson::Array arr; for(auto& r:records){ matjson::Value v; v["id"]=r.levelID; v["normal"]=r.normalPercent; v["practice"]=r.practicePercent; v["attempts"]=r.attempts; v["jumps"]=r.jumps; arr.push_back(v);} std::ofstream o(out); o<<matjson::Value(arr).dump(); return o.good();}
}
